### ISSUE TITLE
OMXPlayer now deprecated.

### ISSUE THREAD

**Issue by ShotokuTech** [alubbock/rpi-vidlooper#13]
Hello.
I tried following your instructions. But sudo apt-get install python3-pip omvplayer fbi returns:
"Package omxplayer is not available..."
Checking the github site for omxplayer, the author indicates it is indeed deprecated.
Is there a workaround that would let me continue with your instructions?
Thank you.

**Comment by hahnix** [comment]
Hi, you have to use the legacy Pi OS (Debian Buster).

**Comment by ShotokuTech** [comment]
Great tip. Worked. Thanks.
