### ISSUE TITLE
Shutdown Button

### ISSUE THREAD

**Issue by GeneArnold** [alubbock/rpi-vidlooper#19]
I'm rather new to Python and I'm trying to figure out the correct place to add a shutdown option into this code. I've tried to add various shutdown options to the PI but since Vidlooper is running my services are not working as planned. Rather than trying to figure that out I thought it would just be easier to add the few lines of code into this project to shutdown the system.

I've got a switch connected to GPIO 21 and I have had success shutting down the system with this pin and other test code. What I need is to add the following into your code 

subprocess.call(['shutdown', '-h', 'now'], shell=False)

And have this called when pin 21 is pressed. Possibly define a method called shutdown? So far this code has been wonderful and I've been able to setup a rather cool display but I would like to have a graceful way of turning the system off.

Thank you!

**Comment by alubbock** [comment]
Hi, I've added an option for this and pushed it to the `master` branch. To use it, install or `git clone` this repo, and start the program with the `--shutdown-pin=21` option. Please could you let me know if this works for you and I'll put it in the next release? Thanks.

**Comment by GeneArnold** [comment]
I will test over the weekend for sure. Do you have a PayPal or method to support / thank you?
@alubbock

**Comment by GeneArnold** [comment]
When I push 21 I get
"The GPIO channel had not been set up as an OUTPUT"
When I push any of the other buttons I get the same error
Guessing just a small change?

**Comment by alubbock** [comment]
Did you change the default GPIO pins for the buttons? Pin 21 is used by default as the output (LED indicator) for the first video. You could either change your shutdown GPIO to an unused pin (e.g. 7), or you can change the button/LED GPIO pins using the `--gpio-pins` option, for example (assuming four videos):

`--gpio-pins 26:7,19:20,13:16,6:12 --shutdown-pin 21`

Each colon-separated pair is the button GPIO pin and the LED GPIO pin. If you're not using LEDs to indicate the active video, you can just give the button GPIO pins:

`--gpio-pins 26,19,13,6 --shutdown-pin 21`

The number of GPIO pins (or pin pairs) needs to match the number of videos you're using.

**Comment by GeneArnold** [comment]
That was my mistake, I forgot about the LED outputs. Once I changed that my video button started working again and the shutdown button is accepted but I get the following error when it is pressed.

TypeError: <lambda>() takes 0 positional arguments but 1 was given

**Comment by alubbock** [comment]
Is that on line 169 `callback=...` ? Sorry about that, I don't have a pi to hand to test it, so I'm coding in the dark a bit. I've pushed a new commit that I think should fix it. If you update to the latest version from `master`, hopefully it'll work now.

**Comment by GeneArnold** [comment]
That did the trick! Thank you so much.

**Comment by alubbock** [comment]
Thanks for testing, this feature is now included in v0.6 on PyPi.
