### ISSUE TITLE
On Screen Text

### ISSUE THREAD

**Issue by philspitlerSF** [alubbock/rpi-vidlooper#3]
When my video gets to the end a loops back I am getting a message on screen that says.

"seek 00:52 00:00" 

I see that in OMXPLAYER there is a flag to turn off on screed display... 

    --no-osd                Do not display status information on screen

Is it possible to have this flag in vidlooper too... I can't really see a need for this on screen display being default.

**Comment by alubbock** [comment]
The OSD shows the video filename, which might be desirable in some circumstances, but you're right that turning off the OSD should be an option. I'll add it in the next version. Thanks for the suggestion!

**Comment by alubbock** [comment]
rpi-vidlooper v0.5 is up on PyPI, which adds a `--no-osd` option. Cheers!
