### ISSUE TITLE
Stop the player

### ISSUE THREAD

**Issue by philspitlerSF** [alubbock/rpi-vidlooper#4]
Is it possible to add a keyboard shortcut to stop vidlooper?

I have is set to run at startup but am now stuck and would love to be able to stop it with my keyboard.

**Comment by alubbock** [comment]
Hi, you should be able to exit with <kbd>Ctrl</kbd>+<kbd>c</kbd>. The video player sometimes doesn't reset the terminal properly on exit, so you may need to type `reset` <kbd>Enter</kbd> after exiting to make the terminal work properly on exit.
